# Generated by Django 3.1.5 on 2021-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(default='hi', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='value'),
        ),
    ]
