# Generated by Django 3.1.5 on 2021-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_auto_20210125_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('value', models.CharField(max_length=1000, verbose_name='value')),
            ],
        ),
    ]
