# Generated by Django 3.1.5 on 2021-04-06 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_auto_20210406_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.CharField(max_length=100, verbose_name='id'),
        ),
    ]
