# Generated by Django 3.1.5 on 2021-04-06 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_auto_20210406_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='userid')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('value', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='userdata',
            name='notes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.usernotes'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='todo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.todo'),
        ),
    ]
