# Generated by Django 3.1.5 on 2021-04-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_auto_20210406_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='notes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.usernotes'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='todo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.todo'),
        ),
    ]
