# Generated by Django 3.1.5 on 2021-04-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_auto_20210406_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='todo',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='UserNotes',
        ),
    ]
